### ISSUE TITLE
NoConversionError: No source can provide "ChampionGGStats"

### ISSUE THREAD

**Issue by xEcEz** [meraki-analytics/cassiopeia-plugins#2]
```python
>>> champions = cassiopeia.get_champions(region="NA")
Making call: https://ddragon.leagueoflegends.com/realms/na.json
Making call: https://ddragon.leagueoflegends.com/cdn/8.10.1/data/en_US/championFull.json
>>> champion_roles = {}
>>> for champion in champions:
...     print(champion.championgg.play_rate)
... 
Making call: https://cdn.rawgit.com/meraki-analytics/cassiopeia/662a3edf/cassiopeia/patches.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/merakicommons/cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Champion' object has no attribute '_lazy__championgg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/merakicommons/cache.py", line 17, in wrapper
    value = method(self)
  File "/usr/local/lib/python3.6/dist-packages/cassiopeia_championgg/__init__.py", line 24, in championgg
    return ChampionGGStats(id=self.id, patch=patch, region=self.region)
  File "/usr/local/lib/python3.6/dist-packages/cassiopeia/core/common.py", line 214, in __call__
    return pipeline.get(cls, query=query)
  File "/usr/local/lib/python3.6/dist-packages/datapipelines/pipelines.py", line 451, in get
    raise NoConversionError("No source can provide \"{type}\"".format(type=type.__name__))
datapipelines.pipelines.NoConversionError: No source can provide "ChampionGGStats"
>>> 
```

**Comment by jjmaldonis** [comment]
Fixed via a change to Cass.
